name: Testing GHA with a Hello World
on:
  # triger on push
  push:
    branches: [main]

  # enable trigger in action UI
  workflow_dispatch:

jobs:
  hello-1:
    # this is the runner this job will run
    runs-on: ubuntu-latest
    
    steps:
    
      - name: A step to print hello world
        run: |
          echo "First line hellow world!"
          echo Second line of echo
          echo Last line of echo
          
      - name: Another step to print
        run: echo Printing without double quotes

  hello-2:

    runs-on: ubuntu-latest

    steps:
    
      - name: Step one of the second job
        run: echo On the second job the first step
        
      - name: Step two of the second job
        run: echo On the second job the second step
